### ISSUE TITLE
Prettier kan ikke formattere visualforce pager

### ISSUE THREAD

**Issue by mamikals** [navikt/crm-workflows-base#44]
Jeg fikk en error når jeg opprettet en ny visualforce page, 
![image](https://github.com/navikt/crm-workflows-base/assets/43532815/26419700-5430-44a9-834b-e9826c044794)
![image](https://github.com/navikt/crm-workflows-base/assets/43532815/ea54c2b2-edda-40f5-bc74-1bb115f5a94e)

**Comment by torhakon** [comment]
@mamikals hvilke repo er det du fikk denne feilen i? Kan være noe i `.prettierrc` filen

**Comment by mamikals** [comment]
@torhakon Det er nok noe med .prettierrc filen som du sier ja 😄, dette var i nks-base repoet

**Comment by torhakon** [comment]
@mamikals får du samme resultat om du kjører noe ala [denne](https://github.com/navikt/crm-workflows-dev/blob/master/.prettierrc), samt bumper versjonen av "prettier-plugin-apex" i `package.json` fila deres

**Comment by mamikals** [comment]
Jeg prøvde denne igjen nå og klarte å fikse problemet med å bare kjøre prettier direkte på filen fra konsollen 
`npx prettier -w force-app\scratch-org\screen-pop\pages\NksCallPage.page`
Så problemet var mest sannsynlig bare extension min eller VS code configen min.
